# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5b346036ce4d9dde1358be7e46c1844c93f8c8157863f65dcb511aeeb20d3f0a984b69fba4aac6568118a7628353488dbe0fbfa6fcd06ef6f500f3620f6a38b

test:
  secret_key_base: e3127a4b508fa3dcbd3aed70e377f3bb86affcc7ddb9d69000117e6ac489957e9084ebb1a2c0bb4e15f3a26c2cc73e18c5af478bd46d7de6628187883cc71913

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
